export const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAMES";
export const GET_VIDEOGAMES_BY_NAME = "GET_VIDEOGAMES_BY_NAME";
export const GET_VIDEOGAMES_BY_ID = "GET_VIDEOGAMES_BY_ID";
export const GET_VIDEOGAMES_BY_FILTER = "GET_VIDEOGAMES_BY_FILTER";
export const GET_VIDEOGAMES_BY_ORDEN = "GET_VIDEOGAMES_BY_ORDEN";
export const GET_PLATFORMS = "GET_PLATFORMS";
export const RESET_FILTER = "RESET_FILTER";